# Site settings
title: Scarfdestroyer
email: bradyrudesill@gmail.com
description:
baseurl: "" # the subpath of your site, e.g. /blog/
url: rudesillb.github.io# the base hostname & protocol for your site
github_username:  rudesillb

# Build settings
markdown: kramdown
